name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install native environment
      run: pio platform install native
    - name: Run PlatformIO
      run: pio test -e native
    -name: Print version numbers
      run: |
        gcc --version
        pio --version
    - name: Run examples
      run: |
        pio ci --verbose --project-conf platformio.ini --keep-build-dir --build-dir="/tmp/bitstring_ci_build1" --lib="." examples/Dynamic\ Sized/dynamic_sized_example.c
        /tmp/bitstring_ci_build1/.pio/build/native/program
        pio ci --verbose --project-conf platformio.ini --keep-build-dir --build-dir="/tmp/bitstring_ci_build2" --lib="." examples/Static\ Sized/static_sized_example.c
        /tmp/bitstring_ci_build2/.pio/build/native/program

